import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/context/AuthContext';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import { useAuth } from '../context/AuthContext';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isAuthorized, role } = useAuth() || {};

  // Si isAuthorized est indéfini, on ne fait rien ou on peut rediriger vers une page de connexion
  if (role && typeof isAuthorized === 'function') {
    // Redirection pour protéger les pages admin
    if (
      !isAuthorized('admin') &&
      typeof window !== 'undefined' &&
      window.location.pathname.startsWith('/admin')
    ) {
      window.location.href = '/';
      return null;
    }

    // Redirection pour protéger les pages super admin
    if (
      !isAuthorized('super-admin') &&
      typeof window !== 'undefined' &&
      window.location.pathname.startsWith('/super-admin')
    ) {
      window.location.href = '/';
      return null;
    }
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
